# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' r-score
#' 
#' This function calculate r-score <doi:10.1007/s00122-019-03387-0> by given training set and test set. 
#' 
#' @author Jen-Hsiang Ou
#' 
#' @param X A numeric matrix. The training set genotypic information matrix can be given as genotype matrix (coded as -1, 0, 1) or principle component matrix (row: sample; column: marker).
#' @param X0 A numeric mareix. The test set genotypic information matrix can be given as genotype matrix (coded as -1, 0, 1) or principle component matrix (row: sample; column: marker).
#' @param lambda A float number. The default value is set as 1.0 and you may change it with the knowledge of heritability.
#' @return A floating-point number, r-score.
#' 
#' @import Rcpp
#' 
#' @export
#' @examples
#' data(geno)
#' \dontrun{r_score(geno[1:50, ], geno[51:100])}
#' @rawNamespace useDynLib(TSDFGS); import(RcppEigen); importFrom(Rcpp, evalCpp)
#' 
r_score <- function(X, X0, lambda = 1.0) {
    .Call('_TSDFGS_r_score', PACKAGE = 'TSDFGS', X, X0, lambda)
}

